import { promises as fs } from "fs";
import path from "path";
import { hashPassword } from "./password";
import { mediaDir, toneWav } from "./media";
import type { Entry, Store, User } from "./types";
import { isoWeekId } from "./week";

const DEMO_PASSWORD = "callboard";

async function ensureTone(name: string, freq: number, seconds: number) {
  try {
    await fs.mkdir(mediaDir(), { recursive: true });
    const file = path.join(mediaDir(), name);
    try {
      await fs.access(file);
    } catch {
      await fs.writeFile(file, toneWav(freq, seconds));
    }
  } catch {
    /* Vercel is read-only; public/seed/*.wav is shipped instead. */
  }
  return `/seed/${name}`;
}

export async function seedStore(store: Store): Promise<Store> {
  const passwordHash = await hashPassword(DEMO_PASSWORD);
  const weekId = isoWeekId();
  const now = Date.now();

  const people: Omit<User, "passwordHash">[] = [
    {
      id: "u_nova",
      email: "nova@callboard.app",
      username: "novavale",
      displayName: "Nova Vale",
      role: "artist",
      cashtag: "$NovaVale",
      bio: "Late-night R&B. Writes in parked cars.",
      createdAt: new Date(now - 20 * 86400000).toISOString(),
    },
    {
      id: "u_kenji",
      email: "kenji@callboard.app",
      username: "kenjipark",
      displayName: "Kenji Park",
      role: "artist",
      cashtag: "$KenjiPark",
      bio: "Alt records that sound like a dashboard at 2am.",
      createdAt: new Date(now - 18 * 86400000).toISOString(),
    },
    {
      id: "u_solange",
      email: "solange@callboard.app",
      username: "solangewren",
      displayName: "Solange Wren",
      role: "artist",
      cashtag: "$SolangeWren",
      bio: "Soul from the waterline.",
      createdAt: new Date(now - 16 * 86400000).toISOString(),
    },
    {
      id: "u_marco",
      email: "marco@callboard.app",
      username: "marcobell",
      displayName: "Marco Bell",
      role: "artist",
      cashtag: "$MarcoBell",
      bio: "Rap that counts the receipt.",
      createdAt: new Date(now - 14 * 86400000).toISOString(),
    },
    {
      id: "u_amara",
      email: "amara@callboard.app",
      username: "amarasol",
      displayName: "Amara Sol",
      role: "artist",
      cashtag: "$AmaraSol",
      bio: "AI-cinematic worlds. Series first.",
      createdAt: new Date(now - 12 * 86400000).toISOString(),
    },
    {
      id: "u_julian",
      email: "julian@callboard.app",
      username: "juliancrowe",
      displayName: "Julian Crowe",
      role: "artist",
      cashtag: "$JulianCrowe",
      bio: "Music videos shot like heists.",
      createdAt: new Date(now - 10 * 86400000).toISOString(),
    },
    {
      id: "u_iris",
      email: "iris@callboard.app",
      username: "irischen",
      displayName: "Iris Chen",
      role: "artist",
      cashtag: "$IrisChen",
      bio: "Prestige-TV scale on an independent budget.",
      createdAt: new Date(now - 8 * 86400000).toISOString(),
    },
  ];

  store.users = people.map((p) => ({ ...p, passwordHash }));

  const wavs = {
    midnight: await ensureTone("seed_midnight.wav", 220, 14),
    engine: await ensureTone("seed_engine.wav", 164.8, 14),
    tide: await ensureTone("seed_tide.wav", 196, 14),
    cash: await ensureTone("seed_cash.wav", 110, 14),
    glass: await ensureTone("seed_glass.wav", 146.8, 18),
    lot: await ensureTone("seed_lot.wav", 130.8, 16),
    season: await ensureTone("seed_season.wav", 174.6, 18),
    last: await ensureTone("seed_last.wav", 123.5, 16),
  };

  const entries: Entry[] = [
    {
      id: "e_midnight",
      slug: "midnight-receipts",
      userId: "u_nova",
      arena: "blind",
      screenKind: null,
      title: "Midnight Receipts",
      genre: "R&B",
      logline: "A quiet flex after the club lights die.",
      coverPath: "/seed/midnight.jpg",
      mediaPath: wavs.midnight,
      durationSeconds: 14,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 4 * 86400000).toISOString(),
      paidAt: new Date(now - 4 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 28,
      scoutPasses: 7,
      heatVotes: 41,
      playCount: 120,
    },
    {
      id: "e_engine",
      slug: "quiet-engine",
      userId: "u_kenji",
      arena: "blind",
      screenKind: null,
      title: "Quiet Engine",
      genre: "Alt",
      logline: "Rain on the windshield. Do not turn the radio on.",
      coverPath: "/seed/engine.jpg",
      mediaPath: wavs.engine,
      durationSeconds: 14,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 3 * 86400000).toISOString(),
      paidAt: new Date(now - 3 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 22,
      scoutPasses: 11,
      heatVotes: 19,
      playCount: 88,
    },
    {
      id: "e_tide",
      slug: "low-tide",
      userId: "u_solange",
      arena: "blind",
      screenKind: null,
      title: "Low Tide",
      genre: "Soul",
      logline: "A voice that arrives after the water leaves.",
      coverPath: "/seed/tide.jpg",
      mediaPath: wavs.tide,
      durationSeconds: 14,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 2 * 86400000).toISOString(),
      paidAt: new Date(now - 2 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 31,
      scoutPasses: 4,
      heatVotes: 27,
      playCount: 101,
    },
    {
      id: "e_cash",
      slug: "after-cash",
      userId: "u_marco",
      arena: "tracks",
      screenKind: null,
      title: "After Cash",
      genre: "Rap",
      logline: "The verse starts when the payment clears.",
      coverPath: "/seed/cash.jpg",
      mediaPath: wavs.cash,
      durationSeconds: 14,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 1 * 86400000).toISOString(),
      paidAt: new Date(now - 1 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 18,
      scoutPasses: 16,
      heatVotes: 55,
      playCount: 140,
    },
    {
      id: "e_glass",
      slug: "glass-kingdom",
      userId: "u_amara",
      arena: "screen",
      screenKind: "series",
      title: "Glass Kingdom",
      genre: "Sci-fi",
      logline: "A palace that should not exist. Episode one teaser.",
      coverPath: "/seed/glass.jpg",
      mediaPath: wavs.glass,
      durationSeconds: 18,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 5 * 86400000).toISOString(),
      paidAt: new Date(now - 5 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 36,
      scoutPasses: 8,
      heatVotes: 62,
      playCount: 210,
    },
    {
      id: "e_lot",
      slug: "run-the-lot",
      userId: "u_julian",
      arena: "screen",
      screenKind: "music-video",
      title: "Run the Lot",
      genre: "Music video",
      logline: "Headlights. Wet asphalt. One take.",
      coverPath: "/seed/lot.jpg",
      mediaPath: wavs.lot,
      durationSeconds: 16,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 3.5 * 86400000).toISOString(),
      paidAt: new Date(now - 3.5 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 24,
      scoutPasses: 9,
      heatVotes: 33,
      playCount: 97,
    },
    {
      id: "e_season",
      slug: "season-zero",
      userId: "u_iris",
      arena: "screen",
      screenKind: "series",
      title: "Season Zero",
      genre: "Drama",
      logline: "Two people on a roof decide whether the city is worth it.",
      coverPath: "/seed/season.jpg",
      mediaPath: wavs.season,
      durationSeconds: 18,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 2.2 * 86400000).toISOString(),
      paidAt: new Date(now - 2.2 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 19,
      scoutPasses: 12,
      heatVotes: 21,
      playCount: 76,
    },
    {
      id: "e_last",
      slug: "last-transmission",
      userId: "u_nova",
      arena: "screen",
      screenKind: "short",
      title: "Last Transmission",
      genre: "Short",
      logline: "Rain on the glass. A face that almost stays.",
      coverPath: "/seed/last.jpg",
      mediaPath: wavs.last,
      durationSeconds: 16,
      hookStartSeconds: 0,
      bytes: 0,
      status: "paid",
      weekId,
      createdAt: new Date(now - 0.8 * 86400000).toISOString(),
      paidAt: new Date(now - 0.8 * 86400000).toISOString(),
      stripeSessionId: "demo",
      potCents: 0,
      houseCents: 0,
      feeCents: 0,
      scoutKeeps: 14,
      scoutPasses: 6,
      heatVotes: 12,
      playCount: 44,
    },
  ];

  store.entries = entries.map((e) => ({
    ...e,
    potCents: 0,
    houseCents: 0,
    feeCents: 0,
    stripeSessionId: "founding",
  }));
  store.houseCents = 0;
  store.chargesLive = false;
  store.chargesLiveAt = null;
  return store;
}
